CREATE TABLE [dbo].[FactSales] (
    [SalesKey]           INT      IDENTITY (1, 1) NOT NULL,
    [OrderID]            INT      NULL,
    [OrderDate]          DATETIME NULL,
    [RequiredDate]       DATETIME NULL,
    [ShippedDate]        DATETIME NULL,
    [DaysToShip]         SMALLINT NULL,
    [DaysOverdue]        SMALLINT NULL,
    [UnitPrice]          MONEY    NULL,
    [Quantity]           SMALLINT NULL,
    [LineTotal]          MONEY    NULL,
    [Freight]            MONEY    NULL,
    [ProductKey]         INT      NULL,
    [CustomerKey]        INT      NULL,
    [SalesPersonKey]     INT      NULL,
    [CategoryKey]        INT      NULL,
    [SupplierKey]        INT      NULL,
    [ShipperKey]         INT      NULL,
    [OrderDateKey]       INT      NULL,
    [RequiredDateKey]    INT      NULL,
    [ShippedDateKey]     INT      NULL,
    [CustomerHistoryKey] INT      NOT NULL,
    CONSTRAINT [pk_FactSales] PRIMARY KEY CLUSTERED ([SalesKey] ASC),
    CONSTRAINT [FK_FactSales_CategoryKey] FOREIGN KEY ([CategoryKey]) REFERENCES [dbo].[DimCategory] ([CategoryKey]),
    CONSTRAINT [fk_FactSales_CustomerHistory] FOREIGN KEY ([CustomerHistoryKey]) REFERENCES [dbo].[DimCustomerHistory] ([CustomerHistoryKey]),
    CONSTRAINT [FK_FactSales_CustomerKey] FOREIGN KEY ([CustomerKey]) REFERENCES [dbo].[DimCustomer] ([CustomerKey]),
    CONSTRAINT [FK_FactSales_OrderDateKey] FOREIGN KEY ([OrderDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_FactSales_ProductKey] FOREIGN KEY ([ProductKey]) REFERENCES [dbo].[DimProduct] ([ProductKey]),
    CONSTRAINT [FK_FactSales_RequiredDateKey] FOREIGN KEY ([RequiredDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_FactSales_SalesPersonKey] FOREIGN KEY ([SalesPersonKey]) REFERENCES [dbo].[DimSalesPerson] ([SalesPersonKey]),
    CONSTRAINT [FK_FactSales_ShippedDateKey] FOREIGN KEY ([ShippedDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_FactSales_ShipperKey] FOREIGN KEY ([ShipperKey]) REFERENCES [dbo].[DimShipper] ([ShipperKey]),
    CONSTRAINT [FK_FactSales_SupplierKey] FOREIGN KEY ([SupplierKey]) REFERENCES [dbo].[DimSupplier] ([SupplierKey])
);

